name: Run tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - run: pip install -r requirements.txt
        name: Install requirements
      - run: pip install flake8 pytest
        name: Install flake8 and pytest
      - run: python -m flake8 .
        name: Run flake8 checks
      - run: python -m pytest test
        name: Run tests
      - run: python tweet.py test
        name: Test tweeter
      - run: python make_list.py
        name: Run make_list.py
